[package]
name = "das-types"
version = "1.7.0"
authors = ["Link <link@blockabc.com>"]
edition = "2018"
license = "MIT"

[dependencies]
molecule = { version = "=0.6.0", default-features = false }
ckb-std = "0.7.1"

[dev-dependencies]
hex = "0.4"
