[package]
name = "das-types"
version = "0.1.0"
authors = ["Link <link@blockabc.com>"]
edition = "2018"

[features]
default = ["std"]
std = ["molecule/std", "ckb-types"]
contract = ["ckb-std"]

[dependencies]
molecule = { version = "0.6", default-features = false }
ckb-std = { version = "0.6", optional = true }
ckb-types = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.38.0", optional = true }

[dev-dependencies]
hex = "0.4"
