[package]
name = "das-types"
version = "0.1.0"
authors = ["Link <link@blockabc.com>"]
edition = "2018"
license = "LGPL-3.0-or-later"

[features]
default = ["std"]
std = ["molecule/std"]

[dependencies]
molecule = { version = "0.6", default-features = false }

[dev-dependencies]
hex = "0.4"
