[package]
name = "das-types"
version = "0.1.0"
authors = ["Link <link@blockabc.com>"]
edition = "2018"

[features]
default = ["std"]
std = ["molecule/std"]

[dependencies]
molecule = { version = "0.6.1", default-features = false }
