[package]
name = "das-types-std"
version = "1.7.0"
authors = ["Link <link@blockabc.com>"]
edition = "2018"
license = "MIT"

[features]

[dependencies]
molecule = { version = "0.7" }
ckb-types = { version = "0.101.4" }

[dev-dependencies]
hex = "0.4"
